name: Test keymap options
on: [pull_request, workflow_dispatch]

jobs:
  build:
    uses: Nuclear-Squid/zmk/.github/workflows/build-user-config.yml@perf/faster-ci
    with:
      archive_name: test-firmwares
      build_matrix_path: tests.yaml
